spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://103.47.241.45:3306/vpmanage?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&serverTimezone=UTC
          username: root
          password: isec@@mysql
          #          url: jdbc:mysql://localhost:20000/vpmanage?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false&serverTimezone=UTC
          #          username: newnoob
          #          password: glbNnLQikZDTRRUvOHOU0pQB
          initialSize: 10
          minIdle: 10
          maxActive: 50
          #配置连接在池中的最小生存时间
#          minEvictableIdleTimeMillis: 30000000
#          validationQuery: SELECT 1 FROM DUAL
#          testWhileIdle: true
#          testOnBorrow: false
#          testOnReturn: false